// This file is generated by the FlutterFire CLI.
// To re-generate it, run `flutterfire configure` in your terminal.

class DefaultFirebaseOptions {
  // This is a placeholder. Replace with your actual Firebase options.
  static const String apiKey = 'your-api-key';
  static const String appId = 'your-app-id';
  static const String messagingSenderId = 'your-messaging-sender-id';
  static const String projectId = 'your-project-id';
}
